/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
import { entityIdSchema } from "./entity.js";
import { noteSchema } from "./note.js";
export const fragmentSelectorSchema = z.unknown() /*zodify can not transform type properly here*/;
export const annotationSchema = z.object({
  id: entityIdSchema,
  targetId: noteSchema.shape["id"],
  selectors: z.array(z.union([z.unknown() /*zodify can not transform type properly here*/, z.unknown() /*zodify can not transform type properly here*/, fragmentSelectorSchema])),
  body: z.string(),
  bodyPlainText: z.string().optional(),
  color: z.string(),
  createdAt: z.number(),
  updatedAt: z.number()
});
export const annotationDTOSchema = z.intersection(annotationSchema.pick({
  "selectors": true,
  "targetId": true
}), annotationSchema.pick({
  "body": true,
  "color": true
}).partial());
export const annotationPatchDTOSchema = annotationSchema.pick({
  "body": true,
  "color": true,
  "selectors": true
}).partial();
export const annotationVOSchema = annotationSchema;