/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
import { entityIdSchema } from "./entity.js";
import { noteSchema } from "./note.js";
export const hTMLCssSelectorSchema = z.object({
  type: z.literal("HTMLCssSelector"),
  value: z.string()
});
export const textFragmentSchema = z.object({
  textStart: z.string(),
  textEnd: z.string().optional(),
  suffix: z.string().optional(),
  prefix: z.string().optional()
});
export const hTMLTextFragmentSelectorSchema = textFragmentSchema.merge(z.object({
  type: z.literal("HTMLTextFragmentSelector")
}));
export const pDFRectSelectorSchema = z.object({
  type: z.literal("PDFRectSelector"),
  page: z.number(),
  top: z.number(),
  left: z.number(),
  width: z.number(),
  height: z.number()
});
export const pDFTextFragmentSelectorSchema = textFragmentSchema.merge(z.object({
  type: z.literal("PDFTextFragmentSelector"),
  startPage: z.number(),
  endPage: z.number(),
  fullText: z.string()
}));
export const selectorSchema = z.union([pDFTextFragmentSelectorSchema, pDFRectSelectorSchema, hTMLTextFragmentSelectorSchema, hTMLCssSelectorSchema]);
export const annotationSchema = z.object({
  id: entityIdSchema,
  targetId: noteSchema.shape["id"],
  selector: selectorSchema,
  body: z.string(),
  bodyPlainText: z.string().optional(),
  color: z.string(),
  createdAt: z.number(),
  updatedAt: z.number()
});
export const annotationDTOSchema = z.intersection(annotationSchema.pick({
  "selector": true,
  "targetId": true
}), annotationSchema.pick({
  "body": true,
  "color": true
}).partial());
export const annotationPatchDTOSchema = annotationSchema.pick({
  "body": true,
  "color": true,
  "selector": true
}).partial();
export const annotationVOSchema = annotationSchema;