/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
import { entitySchema, entityTypesSchema } from "./entity.js";
export const textLocationSchema = z.object({
  start: z.number(),
  end: z.number()
});
export const topicVOSchema = z.object({
  name: z.string(),
  level: z.union([z.literal(1), z.literal(2)]),
  entities: z.array(z.object({
    entity: entitySchema,
    sources: z.array(textLocationSchema)
  }))
});
export const topicQuerySchema = z.object({
  type: entityTypesSchema.optional(),
  level: topicVOSchema.shape["level"].optional()
});