/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
import { entityTypesSchema } from "./entity.js";
export const topicQuerySchema = z.object({
  type: entityTypesSchema.optional()
});