/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
import { EntityTypes } from "../../model/entity.js";
import { fileVOSchema } from "./file.js";
export const entityIdSchema = z.string();
export const entityTypesSchema = z.nativeEnum(EntityTypes);
export const entityParentIdSchema = z.union([entityIdSchema, z.null()]);
const standaloneEntitySchema = z.object({
  id: entityIdSchema,
  type: entityTypesSchema,
  title: z.string(),
  body: z.string().optional(),
  icon: z.union([z.string(), z.null()]),
  file: fileVOSchema.optional(),
  createdAt: z.number(),
  updatedAt: z.number()
});
export const entitySchema = standaloneEntitySchema.merge(z.object({
  main: standaloneEntitySchema.optional()
}));