/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
export const fileSchema = z.object({
  id: z.string(),
  data: z.instanceof(ArrayBuffer),
  size: z.number(),
  hash: z.string(),
  lang: z.array(z.string()),
  mimeType: z.string(),
  textUnitLength: z.number().optional()
});
export const fileDTOSchema = z.object({
  mimeType: fileSchema.shape["mimeType"],
  lang: fileSchema.shape["lang"].optional(),
  data: z.instanceof(ArrayBuffer).optional(),
  path: z.string().optional()
});
export const fileVOSchema = fileSchema.pick({
  "id": true,
  "mimeType": true,
  "lang": true,
  "size": true,
  "hash": true
});
export const textLocationSchema = z.object({
  page: z.number().optional(),
  confidence: z.number().optional(),
  blocks: z.array(z.object({
    bbox: z.object({
      x0: z.number(),
      x1: z.number(),
      y0: z.number(),
      y1: z.number()
    }),
    blocktype: z.union([z.number(), z.string()]),
    paragraphs: z.array(z.object({
      bbox: z.object({
        x0: z.number(),
        x1: z.number(),
        y0: z.number(),
        y1: z.number()
      }),
      is_ltr: z.union([z.literal(0), z.literal(1), z.boolean()]),
      lines: z.array(z.object({
        baseline: z.object({
          x0: z.number(),
          x1: z.number(),
          y0: z.number(),
          y1: z.number()
        }),
        bbox: z.object({
          x0: z.number(),
          x1: z.number(),
          y0: z.number(),
          y1: z.number()
        }),
        text: z.string(),
        confidence: z.number()
      }))
    }))
  })).optional()
});