/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
export const fileSchema = z.object({
  id: z.string(),
  data: z.instanceof(ArrayBuffer),
  size: z.number(),
  hash: z.string(),
  lang: z.array(z.string()),
  mimeType: z.string(),
  isTemp: z.boolean(),
  isTextExtracted: z.boolean().optional()
});
export const fileDTOSchema = z.object({
  mimeType: fileSchema.shape["mimeType"],
  isTemp: z.boolean().optional(),
  lang: fileSchema.shape["lang"].optional(),
  data: z.instanceof(ArrayBuffer).optional(),
  path: z.string().optional()
});
export const fileVOSchema = fileSchema.pick({
  "id": true,
  "mimeType": true,
  "lang": true,
  "size": true,
  "hash": true,
  "isTemp": true
});