/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
export const fileSchema = z.object({
  id: z.string(),
  data: z.instanceof(ArrayBuffer),
  size: z.number(),
  hash: z.string(),
  lang: z.array(z.string()),
  mimeType: z.string(),
  isTextExtracted: z.boolean().optional()
});
export const fileVOSchema = fileSchema.pick({
  "id": true,
  "mimeType": true,
  "lang": true,
  "size": true
});
export const fileDTOSchema = z.intersection(fileSchema.pick({
  "mimeType": true,
  "lang": true
}), z.object({
  data: z.instanceof(ArrayBuffer).optional(),
  path: z.string().optional()
}));