/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
import { entityIdSchema, entityParentIdSchema } from "./entity.js";
import { fileVOSchema } from "./file.js";
export const materialSchema = z.object({
  id: entityIdSchema,
  title: z.string(),
  icon: z.union([z.string(), z.null()]),
  parentId: entityParentIdSchema,
  createdAt: z.number(),
  updatedAt: z.number()
});
export const entityMaterialSchema = materialSchema.merge(z.object({
  file: fileVOSchema,
  body: z.string(),
  sourceUrl: z.union([z.string(), z.null()])
}));
export const materialPatchDTOSchema = entityMaterialSchema.pick({
  "title": true,
  "parentId": true,
  "icon": true,
  "sourceUrl": true,
  "body": true
}).partial();
export const materialBatchPatchDTOSchema = materialPatchDTOSchema.pick({
  "parentId": true,
  "icon": true
});
export const materialDTOSchema = z.intersection(materialPatchDTOSchema, z.object({
  fileId: fileVOSchema.shape["id"].optional()
}));
export const clientMaterialQuerySchema = z.object({
  parentId: z.union([entityParentIdSchema, z.array(z.string())]).optional(),
  fileHash: z.string().optional()
});