/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
import { entityParentIdSchema } from "./entity.js";
export const memoSchema = z.object({
  id: z.string(),
  parentId: entityParentIdSchema,
  isPinned: z.boolean(),
  body: z.string(),
  updatedAt: z.number(),
  createdAt: z.number()
});
export const memoVOSchema = memoSchema.merge(z.object({
  isStar: z.boolean(),
  followupsCount: z.number(),
  referrersCount: z.number()
}));
export const memoDTOSchema = z.object({
  parentId: entityParentIdSchema.optional(),
  body: z.string(),
  isPinned: z.boolean().optional()
});
export const memoPatchDTOSchema = memoDTOSchema.pick({
  "body": true,
  "isPinned": true
}).partial();
export const durationSchema = z.object({
  startTime: z.number().optional(),
  endTime: z.number().optional()
});
export const clientMemoQuerySchema = z.object({
  limit: z.number().optional(),
  orderBy: z.union([z.literal("createdAt"), z.literal("updatedAt")]).optional(),
  order: z.union([z.literal("asc"), z.literal("desc")]).optional(),
  parentId: entityParentIdSchema.optional(),
  isPinned: z.boolean().optional(),
  durations: z.array(durationSchema).optional(),
  endId: memoSchema.shape["id"].optional(),
  startId: memoSchema.shape["id"].optional(),
  tags: z.array(z.string()).optional(),
  keyword: z.string().optional()
});
export const countQuerySchema = clientMemoQuerySchema.pick({
  "durations": true,
  "tags": true
});