/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
import { entityParentIdSchema } from "./entity.js";
import { linkVOSchema } from "./content.js";
export const memoSchema = z.object({
  id: z.string(),
  parentId: entityParentIdSchema,
  isPinned: z.boolean(),
  body: z.string(),
  orderIndex: z.number(),
  updatedAt: z.number(),
  createdAt: z.number()
});
export const memoVOSchema = memoSchema.merge(z.object({
  isStar: z.boolean(),
  childrenCount: z.number(),
  referrers: z.array(linkVOSchema)
}));
export const memoDTOSchema = z.object({
  parentId: entityParentIdSchema.optional(),
  body: z.string(),
  isPinned: z.boolean().optional()
});
export const memoPatchDTOSchema = memoDTOSchema.pick({
  "body": true,
  "isPinned": true
}).partial();
export const durationSchema = z.object({
  startTime: z.number(),
  endTime: z.number()
});
export const clientMemoQuerySchema = z.object({
  limit: z.number(),
  order: z.union([z.literal("asc"), z.literal("desc")]).optional(),
  parentId: entityParentIdSchema.optional(),
  isPinned: z.boolean().optional(),
  startIndex: memoSchema.shape["orderIndex"].optional(),
  endIndex: memoSchema.shape["orderIndex"].optional(),
  startTime: z.number().optional(),
  endTime: z.number().optional()
});