/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
import { NoteTypes } from "../../model/note.js";
import { entityIdSchema, entityParentIdSchema } from "./entity.js";
export const noteTypesSchema = z.nativeEnum(NoteTypes);
export const noteSchema = z.object({
  id: entityIdSchema,
  type: noteTypesSchema,
  title: z.string(),
  parentId: entityParentIdSchema,
  body: z.string().optional(),
  icon: z.union([z.string(), z.null()]),
  fileId: z.union([z.string(), z.null()]).optional(),
  mimeType: z.union([z.string(), z.null()]),
  sourceUrl: z.union([z.string(), z.null()]),
  updatedAt: z.number(),
  createdAt: z.number()
});
export const notePatchDTOSchema = noteSchema.pick({
  "title": true,
  "parentId": true,
  "icon": true,
  "body": true
}).partial();
export const duplicatedNoteDTOSchema = z.object({
  from: noteSchema.shape["id"]
});
export const noteBatchPatchDTOSchema = notePatchDTOSchema.pick({
  "parentId": true
});
export const newNoteDTOSchema = z.intersection(noteSchema.pick({
  "body": true,
  "fileId": true,
  "icon": true,
  "parentId": true,
  "sourceUrl": true,
  "title": true
}).partial(), noteSchema.pick({
  "type": true
}).required());
export const noteDTOSchema = z.union([newNoteDTOSchema, duplicatedNoteDTOSchema]);
export const clientNoteQuerySchema = z.object({
  type: noteSchema.shape["type"].optional(),
  parentId: z.union([entityParentIdSchema, z.array(z.string())]).optional(),
  fileHash: z.string().optional()
});