/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
import { entityIdSchema, entityParentIdSchema, iconSchema } from "./entity.js";
export const noteSchema = z.object({
  id: entityIdSchema,
  title: z.string(),
  parentId: entityParentIdSchema,
  body: z.string().optional(),
  icon: z.union([iconSchema, z.null()]),
  fileId: z.union([z.string(), z.null()]),
  mimeType: z.union([z.string(), z.null()]),
  sourceUrl: z.union([z.string(), z.null()]),
  updatedAt: z.number(),
  createdAt: z.number()
});
export const notePatchDTOSchema = noteSchema.pick({
  "title": true,
  "parentId": true,
  "icon": true,
  "body": true
}).partial();
export const duplicatedNoteDTOSchema = z.object({
  from: noteSchema.shape["id"]
});
export const newNoteDTOSchema = noteSchema.pick({
  "body": true,
  "fileId": true,
  "icon": true,
  "parentId": true,
  "sourceUrl": true,
  "title": true
}).partial();
export const noteDTOSchema = z.union([duplicatedNoteDTOSchema, newNoteDTOSchema]);
export const clientNoteQuerySchema = z.object({
  id: z.array(noteSchema.shape["id"]).optional(),
  parentId: z.union([entityParentIdSchema, z.array(z.string())]).optional(),
  fileHash: z.string().optional()
});
export const fileTextQuerySchema = z.object({
  id: noteSchema.shape["id"],
  pages: z.array(z.number()).optional()
});