/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
import { entityIdSchema } from "./entity.js";
export const revisionSchema = z.object({
  id: entityIdSchema,
  entityId: entityIdSchema,
  titleDiff: z.union([z.unknown() /*zodify can not transform type properly here*/, z.null()]),
  bodyDiff: z.union([z.unknown() /*zodify can not transform type properly here*/, z.null()]),
  previousId: z.union([entityIdSchema, z.null()]),
  appName: z.string(),
  deviceName: z.string(),
  name: z.union([z.string(), z.null()]),
  createdAt: z.number(),
  isAuto: z.boolean()
});
export const revisionPatchDTOSchema = revisionSchema.pick({
  "name": true
});