/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
import { entityIdSchema } from "./entity.js";
export const starDTOSchema = z.object({
  entityId: entityIdSchema
});