/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
import { SelectorTypes } from "../../model/annotation.js";
import { entityIdSchema } from "./entity.js";
export const selectorTypesSchema = z.nativeEnum(SelectorTypes);
const cssSelectorSchema = z.object({
  type: z.literal(selectorTypesSchema.enum.CSS),
  value: z.string(),
  offset: z.string().optional()
});
const rangeSelectorSchema = z.object({
  type: z.literal(selectorTypesSchema.enum.Range),
  start: cssSelectorSchema,
  end: cssSelectorSchema
});
export const fragmentSelectorSchema = z.object({
  type: z.literal(selectorTypesSchema.enum.Fragment),
  value: z.string()
});
const selectorSchema = z.union([cssSelectorSchema, fragmentSelectorSchema, rangeSelectorSchema]);
export const annotationDTOSchema = z.object({
  targetId: z.string(),
  selectors: z.array(selectorSchema),
  body: z.string().optional(),
  targetText: z.union([z.string(), z.null()]).optional(),
  color: z.string()
});
export const annotationPatchDTOSchema = annotationDTOSchema.pick({
  "body": true,
  "color": true
});
export const annotationSchema = z.object({
  id: entityIdSchema,
  targetId: entityIdSchema,
  targetText: z.union([z.string(), z.null()]),
  selectors: z.array(selectorSchema),
  body: z.string(),
  color: z.string(),
  createdAt: z.number(),
  updatedAt: z.number()
});
export const annotationVOSchema = annotationSchema;