/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
const uneditableConfigSchema = z.object({
  'httpServer.enabled': z.boolean()
}).partial();
export const editableConfigSchema = z.object({
  unknown: z.string()
}).partial();
export const configSchema = z.intersection(editableConfigSchema, uneditableConfigSchema);
export const configDTOSchema = configSchema;
export const configVOSchema = configSchema;