/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
import { entitySchema } from "./entity.js";
import { fragmentSelectorSchema } from "./annotation.js";
export const snippetSchema = z.object({
  text: z.string(),
  highlightStart: z.number(),
  highlightEnd: z.number()
});
const offsetSchema = z.object({
  start: z.number(),
  end: z.number()
});
export const linkVOSchema = z.object({
  entity: entitySchema,
  links: z.array(z.object({
    targetSelector: fragmentSelectorSchema.optional(),
    sourceLocation: offsetSchema,
    sourceSnippet: snippetSchema
  }))
});