/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
import { entitySchema } from "./entity.js";
export const textLocationSchema = z.object({
  start: z.number(),
  end: z.number()
});
export const snippetSchema = z.object({
  text: z.string(),
  highlight: textLocationSchema.optional()
});
export const referenceSchema = z.object({
  entity: entitySchema,
  sourceLocation: textLocationSchema,
  sourceSnippet: snippetSchema.required(),
  targetFragmentId: z.union([z.string(), z.null()]),
  targetSnippet: snippetSchema
});
export const referrerSchema = z.object({
  entity: entitySchema,
  references: z.array(referenceSchema)
});