/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
import { EntityTypes } from "../../model/entity.js";
export const entityIdSchema = z.string();
export const entityTypesSchema = z.nativeEnum(EntityTypes);
export const entityLocatorSchema = z.object({
  entityId: entityIdSchema,
  entityType: entityTypesSchema
});
export const entityParentIdSchema = z.union([entityIdSchema, z.null()]);