/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
import { entityIdSchema } from "./entity.js";
export const fileDTOSchema = z.object({
  mimeType: z.string(),
  data: z.instanceof(ArrayBuffer).optional(),
  path: z.string().optional(),
  lang: z.array(z.string())
});
export const fileVOSchema = z.object({
  id: entityIdSchema,
  mimeType: z.string(),
  size: z.number(),
  lang: z.array(z.string())
});