/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
export const commonFragmentSchema = z.record(z.string());
export const textQuoteFragmentSchema = z.object({
  start: z.string(),
  end: z.string().optional(),
  prefix: z.string().optional(),
  suffix: z.string().optional()
});