/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
import { entityParentIdSchema, entityIdSchema } from "./entity.js";
export const materialDTOSchema = z.object({
  title: z.string().optional(),
  parentId: entityParentIdSchema.optional(),
  icon: z.union([z.string(), z.null()]).optional(),
  fileId: z.string().optional(),
  sourceUrl: z.union([z.string(), z.null()]).optional(),
  comment: z.string().optional()
});
export const materialPatchDTOSchema = materialDTOSchema.omit({
  "fileId": true
});
export const clientMaterialQuerySchema = z.object({
  parentId: z.union([entityParentIdSchema, z.array(z.string())]).optional(),
  fileHash: z.string().optional()
});
export const materialSchema = z.object({
  id: entityIdSchema,
  title: z.string(),
  icon: z.union([z.string(), z.null()]),
  parentId: entityParentIdSchema,
  createdAt: z.number(),
  updatedAt: z.number()
});
export const materialVOSchema = materialSchema.merge(z.object({
  childrenCount: z.number(),
  isStar: z.boolean()
}));