/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
import { entityParentIdSchema, entityIdSchema } from "./entity.js";
export const notePatchDTOSchema = z.object({
  title: z.string().optional(),
  parentId: entityParentIdSchema.optional(),
  icon: z.union([z.string(), z.null()]).optional(),
  body: z.string().optional()
});
export const clientNoteQuerySchema = z.object({
  parentId: z.union([z.array(z.string()), z.string(), z.null()]).optional()
});
export const noteDTOSchema = notePatchDTOSchema;
export const noteSchema = z.object({
  title: z.string(),
  id: entityIdSchema,
  parentId: entityParentIdSchema,
  icon: z.union([z.string(), z.null()]),
  updatedAt: z.number(),
  createdAt: z.number(),
  body: z.string().optional()
});
export const noteVOSchema = noteSchema.merge(z.object({
  isStar: z.boolean(),
  childrenCount: z.number(),
  diff: z.unknown() /*zodify can not transform type properly here*/
}));