/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
import { entityIdSchema, entityParentIdSchema } from "./entity.js";
export const noteSchema = z.object({
  title: z.string(),
  id: entityIdSchema,
  parentId: entityParentIdSchema,
  body: z.string().optional(),
  icon: z.union([z.string(), z.null()]),
  updatedAt: z.number(),
  createdAt: z.number()
});
export const notePatchDTOSchema = noteSchema.pick({
  "title": true,
  "parentId": true,
  "icon": true,
  "body": true
}).partial();
export const noteBatchPatchDTOSchema = notePatchDTOSchema.pick({
  "icon": true,
  "parentId": true
});
export const noteDTOSchema = z.intersection(notePatchDTOSchema, z.object({
  from: noteSchema.shape["id"].optional()
}));
export const clientNoteQuerySchema = z.object({
  parentId: z.union([entityParentIdSchema, z.array(z.string())]).optional()
});