/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
import { entityIdSchema } from "./entity.js";
export const recyclableDTOSchema = z.object({
  entityId: entityIdSchema
});
export const recyclablesDTOSchema = z.array(recyclableDTOSchema);