/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
import { entityIdSchema } from "./entity.js";
export const starSchema = z.object({
  entityId: entityIdSchema,
  createdAt: z.number()
});
export const starDTOSchema = starSchema.pick({
  "entityId": true
});