/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
import { entityIdSchema, entityLocatorSchema } from "./entity.js";
export const starDTOSchema = z.object({
  entityId: entityIdSchema
});
export const starVOSchema = entityLocatorSchema.merge(z.object({
  mimeType: z.string().optional(),
  title: z.string(),
  mainEntityId: entityIdSchema.optional(),
  icon: z.union([z.string(), z.null()])
}));