/*
* THIS FILE WAS GENERATED BY ZODIFY 
* DO NOT EDIT THIS FILE MANUALLY
*/
import { z } from "zod";
import { entityIdSchema } from "./entity.js";
export const versionDTOSchema = z.object({
  entityId: entityIdSchema,
  comment: z.string().optional()
});
export const versionMergeRequestSchema = z.object({
  entityId: entityIdSchema,
  startIndex: z.number(),
  endIndex: z.number(),
  comment: z.string().optional()
});
export const versionSchema = z.object({
  id: z.string().optional(),
  comment: z.string(),
  entityId: entityIdSchema,
  device: z.string(),
  diff: z.string(),
  isAuto: z.boolean(),
  index: z.number(),
  createdAt: z.number()
});
export const versionVOSchema = versionSchema.omit({
  "id": true
});